name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-22.04  # Use Ubuntu 22.04 instead of ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install Required Linux Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            xvfb \
            libnss3 \
            libatk1.0-0 \
            libatk-bridge2.0-0 \
            libxcomposite1 \
            libxdamage1 \
            libxrandr2 \
            libgbm1 \
            libasound2t64 \
            libpangocairo-1.0-0 \
            libpango-1.0-0 \
            libcups2 \
            libx11-xcb1 \
            libxcursor1 \
            libxss1 \
            libwayland-client0 \
            libwayland-egl1 \
            libwayland-server0 \
            libappindicator3-1 \
            libgdk-pixbuf-2.0-0 \
            libatspi2.0-0 \
            fonts-liberation \
            libcurl4

      - name: Install Cypress Binary
        run: npx cypress install

      - name: Run Cypress tests with Xvfb
        run: xvfb-run --auto-servernum npx cypress run